package com.grechur.wanandroid.model.entity;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ARTICLE".
*/
public class ArticleDao extends AbstractDao<Article, Long> {

    public static final String TABLENAME = "ARTICLE";

    /**
     * Properties of entity Article.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Author = new Property(0, String.class, "author", false, "AUTHOR");
        public final static Property ApkLink = new Property(1, String.class, "apkLink", false, "APK_LINK");
        public final static Property ChapterId = new Property(2, int.class, "chapterId", false, "CHAPTER_ID");
        public final static Property ChapterName = new Property(3, String.class, "chapterName", false, "CHAPTER_NAME");
        public final static Property Collect = new Property(4, boolean.class, "collect", false, "COLLECT");
        public final static Property CourseId = new Property(5, int.class, "courseId", false, "COURSE_ID");
        public final static Property Desc = new Property(6, String.class, "desc", false, "DESC");
        public final static Property EnvelopePic = new Property(7, String.class, "envelopePic", false, "ENVELOPE_PIC");
        public final static Property Id = new Property(8, Long.class, "id", true, "_id");
        public final static Property Fresh = new Property(9, boolean.class, "fresh", false, "FRESH");
        public final static Property Link = new Property(10, String.class, "link", false, "LINK");
        public final static Property NiceDate = new Property(11, String.class, "niceDate", false, "NICE_DATE");
        public final static Property Origin = new Property(12, String.class, "origin", false, "ORIGIN");
        public final static Property ProjectLink = new Property(13, String.class, "projectLink", false, "PROJECT_LINK");
        public final static Property PublishTime = new Property(14, long.class, "publishTime", false, "PUBLISH_TIME");
        public final static Property SuperChapterName = new Property(15, String.class, "superChapterName", false, "SUPER_CHAPTER_NAME");
        public final static Property SuperChapterId = new Property(16, int.class, "superChapterId", false, "SUPER_CHAPTER_ID");
        public final static Property Title = new Property(17, String.class, "title", false, "TITLE");
        public final static Property Type = new Property(18, int.class, "type", false, "TYPE");
        public final static Property UserId = new Property(19, int.class, "userId", false, "USER_ID");
        public final static Property Visible = new Property(20, int.class, "visible", false, "VISIBLE");
        public final static Property Zan = new Property(21, int.class, "zan", false, "ZAN");
    }


    public ArticleDao(DaoConfig config) {
        super(config);
    }
    
    public ArticleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ARTICLE\" (" + //
                "\"AUTHOR\" TEXT," + // 0: author
                "\"APK_LINK\" TEXT," + // 1: apkLink
                "\"CHAPTER_ID\" INTEGER NOT NULL ," + // 2: chapterId
                "\"CHAPTER_NAME\" TEXT," + // 3: chapterName
                "\"COLLECT\" INTEGER NOT NULL ," + // 4: collect
                "\"COURSE_ID\" INTEGER NOT NULL ," + // 5: courseId
                "\"DESC\" TEXT," + // 6: desc
                "\"ENVELOPE_PIC\" TEXT," + // 7: envelopePic
                "\"_id\" INTEGER PRIMARY KEY ," + // 8: id
                "\"FRESH\" INTEGER NOT NULL ," + // 9: fresh
                "\"LINK\" TEXT," + // 10: link
                "\"NICE_DATE\" TEXT," + // 11: niceDate
                "\"ORIGIN\" TEXT," + // 12: origin
                "\"PROJECT_LINK\" TEXT," + // 13: projectLink
                "\"PUBLISH_TIME\" INTEGER NOT NULL ," + // 14: publishTime
                "\"SUPER_CHAPTER_NAME\" TEXT," + // 15: superChapterName
                "\"SUPER_CHAPTER_ID\" INTEGER NOT NULL ," + // 16: superChapterId
                "\"TITLE\" TEXT," + // 17: title
                "\"TYPE\" INTEGER NOT NULL ," + // 18: type
                "\"USER_ID\" INTEGER NOT NULL ," + // 19: userId
                "\"VISIBLE\" INTEGER NOT NULL ," + // 20: visible
                "\"ZAN\" INTEGER NOT NULL );"); // 21: zan
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ARTICLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Article entity) {
        stmt.clearBindings();
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(1, author);
        }
 
        String apkLink = entity.getApkLink();
        if (apkLink != null) {
            stmt.bindString(2, apkLink);
        }
        stmt.bindLong(3, entity.getChapterId());
 
        String chapterName = entity.getChapterName();
        if (chapterName != null) {
            stmt.bindString(4, chapterName);
        }
        stmt.bindLong(5, entity.getCollect() ? 1L: 0L);
        stmt.bindLong(6, entity.getCourseId());
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(7, desc);
        }
 
        String envelopePic = entity.getEnvelopePic();
        if (envelopePic != null) {
            stmt.bindString(8, envelopePic);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(9, id);
        }
        stmt.bindLong(10, entity.getFresh() ? 1L: 0L);
 
        String link = entity.getLink();
        if (link != null) {
            stmt.bindString(11, link);
        }
 
        String niceDate = entity.getNiceDate();
        if (niceDate != null) {
            stmt.bindString(12, niceDate);
        }
 
        String origin = entity.getOrigin();
        if (origin != null) {
            stmt.bindString(13, origin);
        }
 
        String projectLink = entity.getProjectLink();
        if (projectLink != null) {
            stmt.bindString(14, projectLink);
        }
        stmt.bindLong(15, entity.getPublishTime());
 
        String superChapterName = entity.getSuperChapterName();
        if (superChapterName != null) {
            stmt.bindString(16, superChapterName);
        }
        stmt.bindLong(17, entity.getSuperChapterId());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(18, title);
        }
        stmt.bindLong(19, entity.getType());
        stmt.bindLong(20, entity.getUserId());
        stmt.bindLong(21, entity.getVisible());
        stmt.bindLong(22, entity.getZan());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Article entity) {
        stmt.clearBindings();
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(1, author);
        }
 
        String apkLink = entity.getApkLink();
        if (apkLink != null) {
            stmt.bindString(2, apkLink);
        }
        stmt.bindLong(3, entity.getChapterId());
 
        String chapterName = entity.getChapterName();
        if (chapterName != null) {
            stmt.bindString(4, chapterName);
        }
        stmt.bindLong(5, entity.getCollect() ? 1L: 0L);
        stmt.bindLong(6, entity.getCourseId());
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(7, desc);
        }
 
        String envelopePic = entity.getEnvelopePic();
        if (envelopePic != null) {
            stmt.bindString(8, envelopePic);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(9, id);
        }
        stmt.bindLong(10, entity.getFresh() ? 1L: 0L);
 
        String link = entity.getLink();
        if (link != null) {
            stmt.bindString(11, link);
        }
 
        String niceDate = entity.getNiceDate();
        if (niceDate != null) {
            stmt.bindString(12, niceDate);
        }
 
        String origin = entity.getOrigin();
        if (origin != null) {
            stmt.bindString(13, origin);
        }
 
        String projectLink = entity.getProjectLink();
        if (projectLink != null) {
            stmt.bindString(14, projectLink);
        }
        stmt.bindLong(15, entity.getPublishTime());
 
        String superChapterName = entity.getSuperChapterName();
        if (superChapterName != null) {
            stmt.bindString(16, superChapterName);
        }
        stmt.bindLong(17, entity.getSuperChapterId());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(18, title);
        }
        stmt.bindLong(19, entity.getType());
        stmt.bindLong(20, entity.getUserId());
        stmt.bindLong(21, entity.getVisible());
        stmt.bindLong(22, entity.getZan());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8);
    }    

    @Override
    public Article readEntity(Cursor cursor, int offset) {
        Article entity = new Article( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // author
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // apkLink
            cursor.getInt(offset + 2), // chapterId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // chapterName
            cursor.getShort(offset + 4) != 0, // collect
            cursor.getInt(offset + 5), // courseId
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // desc
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // envelopePic
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8), // id
            cursor.getShort(offset + 9) != 0, // fresh
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // link
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // niceDate
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // origin
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // projectLink
            cursor.getLong(offset + 14), // publishTime
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // superChapterName
            cursor.getInt(offset + 16), // superChapterId
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // title
            cursor.getInt(offset + 18), // type
            cursor.getInt(offset + 19), // userId
            cursor.getInt(offset + 20), // visible
            cursor.getInt(offset + 21) // zan
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Article entity, int offset) {
        entity.setAuthor(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setApkLink(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setChapterId(cursor.getInt(offset + 2));
        entity.setChapterName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCollect(cursor.getShort(offset + 4) != 0);
        entity.setCourseId(cursor.getInt(offset + 5));
        entity.setDesc(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setEnvelopePic(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setId(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
        entity.setFresh(cursor.getShort(offset + 9) != 0);
        entity.setLink(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setNiceDate(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setOrigin(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setProjectLink(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setPublishTime(cursor.getLong(offset + 14));
        entity.setSuperChapterName(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setSuperChapterId(cursor.getInt(offset + 16));
        entity.setTitle(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setType(cursor.getInt(offset + 18));
        entity.setUserId(cursor.getInt(offset + 19));
        entity.setVisible(cursor.getInt(offset + 20));
        entity.setZan(cursor.getInt(offset + 21));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Article entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Article entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Article entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
