package com.grechur.wanandroid.model.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.grechur.wanandroid.model.entity.Article;
import com.grechur.wanandroid.model.entity.navigation.NaviArticle;

import com.grechur.wanandroid.model.entity.ArticleDao;
import com.grechur.wanandroid.model.entity.navigation.NaviArticleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig articleDaoConfig;
    private final DaoConfig naviArticleDaoConfig;

    private final ArticleDao articleDao;
    private final NaviArticleDao naviArticleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        articleDaoConfig = daoConfigMap.get(ArticleDao.class).clone();
        articleDaoConfig.initIdentityScope(type);

        naviArticleDaoConfig = daoConfigMap.get(NaviArticleDao.class).clone();
        naviArticleDaoConfig.initIdentityScope(type);

        articleDao = new ArticleDao(articleDaoConfig, this);
        naviArticleDao = new NaviArticleDao(naviArticleDaoConfig, this);

        registerDao(Article.class, articleDao);
        registerDao(NaviArticle.class, naviArticleDao);
    }
    
    public void clear() {
        articleDaoConfig.clearIdentityScope();
        naviArticleDaoConfig.clearIdentityScope();
    }

    public ArticleDao getArticleDao() {
        return articleDao;
    }

    public NaviArticleDao getNaviArticleDao() {
        return naviArticleDao;
    }

}
